# Generated by Django 5.1.2 on 2024-10-28 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_type', models.CharField(choices=[('DR', 'Driver'), ('3W', '3 Wood'), ('5W', '5 Wood'), ('7W', '7 Wood'), ('2I', '2 Iron'), ('3I', '3 Iron'), ('4I', '4 Iron'), ('5I', '5 Iron'), ('6I', '6 Iron'), ('7I', '7 Iron'), ('8I', '8 Iron'), ('9I', '9 Iron'), ('PW', 'Pitching Wedge (46°)'), ('50', '50° Wedge'), ('52', '52° Wedge'), ('54', '54° Wedge'), ('56', '56° Wedge'), ('58', '58° Wedge'), ('60', '60° Wedge'), ('62', '62° Wedge'), ('2H', '2 Hybrid'), ('3H', '3 Hybrid'), ('4H', '4 Hybrid'), ('5H', '5 Hybrid'), ('UI', 'Utility Iron')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clubs', models.ManyToManyField(to='clubs.club')),
            ],
        ),
    ]
