# Generated by Django 5.1.2 on 2024-10-29 09:08

# Generated by Django 4.2.7
from django.db import migrations

def create_clubs(apps, schema_editor):
    # Get the Club model from the app registry
    # We can't import Club directly as it may be a newer version than this migration expects
    Club = apps.get_model('clubs', 'Club')
    
    # Create all club types from CLUB_CHOICES
    clubs_to_create = [
        # Woods
        ('DR', 'Driver'),
        ('3W', '3 Wood'),
        ('5W', '5 Wood'),
        ('7W', '7 Wood'),
        
        # Irons
        ('2I', '2 Iron'),
        ('3I', '3 Iron'),
        ('4I', '4 Iron'),
        ('5I', '5 Iron'),
        ('6I', '6 Iron'),
        ('7I', '7 Iron'),
        ('8I', '8 Iron'),
        ('9I', '9 Iron'),
        
        # Wedges
        ('PW', 'Pitching Wedge (46°)'),
        ('50', '50° Wedge'),
        ('52', '52° Wedge'),
        ('54', '54° Wedge'),
        ('56', '56° Wedge'),
        ('58', '58° Wedge'),
        ('60', '60° Wedge'),
        ('62', '62° Wedge'),
        
        # Hybrids
        ('2H', '2 Hybrid'),
        ('3H', '3 Hybrid'),
        ('4H', '4 Hybrid'),
        ('5H', '5 Hybrid'),
        
        # Utility
        ('UI', 'Utility Iron'),
    ]
    
    # Create each club in the database
    for club_type, _ in clubs_to_create:
        Club.objects.create(club_type=club_type)

def remove_clubs(apps, schema_editor):
    # Get the Club model
    Club = apps.get_model('clubs', 'Club')
    # Delete all clubs
    Club.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),  # Make sure this matches your last migration
    ]

    operations = [
        migrations.RunPython(create_clubs, remove_clubs),
    ]