# Generated by Django 5.1.2 on 2024-11-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20241029_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bag',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_type',
            field=models.CharField(choices=[('DR', 'Driver'), ('3W', '3 Wood'), ('5W', '5 Wood'), ('7W', '7 Wood'), ('2I', '2 Iron'), ('3I', '3 Iron'), ('4I', '4 Iron'), ('5I', '5 Iron'), ('6I', '6 Iron'), ('7I', '7 Iron'), ('8I', '8 Iron'), ('9I', '9 Iron'), ('PW', 'Pitching Wedge'), ('50', '50° Wedge'), ('52', '52° Wedge'), ('54', '54° Wedge'), ('56', '56° Wedge'), ('58', '58° Wedge'), ('60', '60° Wedge'), ('62', '62° Wedge'), ('2H', '2 Hybrid'), ('3H', '3 Hybrid'), ('4H', '4 Hybrid'), ('5H', '5 Hybrid'), ('UI', 'Utility Iron')], max_length=2),
        ),
    ]
